apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: twenty-db
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.14-system-trixie
  bootstrap:
    initdb:
      database: twenty
      owner: twenty
  storage:
    storageClass: longhorn
    size: 20Gi
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
