apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: twenty-server
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      app.kubernetes.io/name: twenty-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: twenty-worker
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      app.kubernetes.io/name: twenty-worker
