- op: replace
  path: /metadata/name
  value: twenty-backup
- op: replace
  path: /spec/backend/repoPasswordSecretRef/name
  value: twenty-k8up-repo-password
- op: replace
  path: /spec/backend/s3/bucket
  value: sgfdevs-on-prem-k3s-backups/twenty
- op: replace
  path: /spec/backup/schedule
  value: '0 6 * * *'
- op: replace
  path: /spec/backup/labelSelectors/0/matchLabels/backup.k8up.io~1app
  value: twenty
