apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    vault:
      server: http://openbao-active.openbao.svc.cluster.local:8200
      path: applications
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: twenty-secrets
          serviceAccountRef:
            name: twenty-secrets
            audiences:
              - vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twenty
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: twenty
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: twenty/app
        property: appSecret
    - secretKey: EMAIL_SMTP_USER
      remoteRef:
        key: twenty/ses
        property: username
    - secretKey: EMAIL_SMTP_PASSWORD
      remoteRef:
        key: twenty/ses
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twenty-preview-auth
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: twenty-preview-auth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: twenty/app
        property: previewHtpasswd
