apiVersion: v1
kind: ServiceAccount
metadata:
  name: twenty-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    infra.sgf.dev/aws-role-arn: "arn:aws:iam::${SGFDEVS_AWS_ACCOUNT_ID}:role/sgfdevs-k3s/sgfdevs-k3s-twenty"
automountServiceAccountToken: false
