apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plausible-restore-workflow
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    resourceNames: ["plausible"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plausible-restore-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: plausible-restore-workflow
subjects:
  - kind: ServiceAccount
    name: plausible-restore-workflow
    namespace: plausible
