apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oauth2-proxy-k8s
  target:
    name: oauth2-proxy
    template:
      mergePolicy: Merge
      data:
        client-id: oauth2-proxy
  data:
    - secretKey: client-secret
      remoteRef:
        key: oauth2-proxy-secrets
        property: oauth2ProxyClientSecret
    - secretKey: cookie-secret
      remoteRef:
        key: oauth2-proxy-secrets
        property: cookieSecret
