apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sgf-dev-backup
spec:
  entrypoint: backup
  serviceAccountName: sgf-dev-backup-workflow
  synchronization:
    mutexes:
      - name: sgf-dev-maintenance
  activeDeadlineSeconds: 3600
  ttlStrategy:
    secondsAfterCompletion: 86400
  podGC:
    strategy: OnWorkflowCompletion
    deleteDelayDuration: 10m
  templates:
    - name: backup
      resource:
        action: create
        successCondition: status.conditions.#(type=="Completed").reason == Succeeded
        failureCondition: status.conditions.#(type=="Completed").reason == Failed
        manifest: |
          apiVersion: k8up.io/v1
          kind: Backup
          metadata:
            name: sgf-dev-on-demand-{{workflow.uid}}
          spec:
            failedJobsHistoryLimit: 2
            successfulJobsHistoryLimit: 2
            tags:
              - {{workflow.namespace}}
              - sgf-dev
              - on-demand
            labelSelectors:
              - matchLabels:
                  backup.k8up.io/app: sgf-dev
            backend:
              repoPasswordSecretRef:
                name: sgf-dev-k8up-repo-password
                key: password
              b2:
                bucket: sgfdevs-on-prem-k3s-backups
                path: {{workflow.namespace}}
                accountIDSecretRef:
                  name: k8up-b2-credentials
                  key: account-id
                accountKeySecretRef:
                  name: k8up-b2-credentials
                  key: account-key
