apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sgf-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: sgf-dev
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SGFDevs__AzureBlobStorageKey
      remoteRef:
        key: sgf-dev/application
        property: azureBlobStorageKey
    - secretKey: SGFDevs__MeetupApi__ClientSecret
      remoteRef:
        key: sgf-dev/application
        property: meetupApiClientSecret
    - secretKey: Sentry__Dsn
      remoteRef:
        key: sgf-dev/application
        property: sentryDsn
    - secretKey: Umbraco__CMS__Global__Smtp__Username
      remoteRef:
        key: sgf-dev/ses
        property: username
    - secretKey: Umbraco__CMS__Global__Smtp__Password
      remoteRef:
        key: sgf-dev/ses
        property: password
