apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - secret-store.yaml
  - external-secret.yaml
  - configmap.yaml
  - pvc.yaml
  - image-prepuller.yaml
  - deployment.yaml
  - service.yaml
  - middleware-https-redirect.yaml
  - certificate.yaml
  - ingress.yaml
  - workflow-rbac.yaml
  - workflow-scripts.yaml
  - backup-workflowtemplate.yaml
  - restore-workflowtemplate.yaml
