apiVersion: kinda.rocks/v1beta1
kind: Database
metadata:
  name: wordpress-migration
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  instance: hack4goodsgf-staging-mysql-migration
  secretName: hack4goodsgf-wordpress-database-migration
  deletionProtected: true
