apiVersion: kinda.rocks/v1beta1
kind: DbInstance
metadata:
  name: hack4goodsgf-staging-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  engine: mysql
  adminSecretRef:
    Name: hack4goodsgf-mysql-mysql-account-root
    Namespace: hack4goodsgf-com-staging
  generic:
    host: hack4goodsgf-mysql-mysql.hack4goodsgf-com-staging.svc.cluster.local
    port: 3306
