apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hack4goodsgf-smtp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: hack4goodsgf-smtp
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: WORDPRESS_SMTP_USERNAME
      remoteRef:
        key: hack4goodsgf/staging/ses
        property: username
    - secretKey: WORDPRESS_SMTP_PASSWORD
      remoteRef:
        key: hack4goodsgf/staging/ses
        property: password
