apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hack4goodsgf-com-staging
resources:
  - ../base
  - namespace.yaml
  - service-account.yaml
  - secret-store.yaml
  - external-secret.yaml
  - wordpress-admin-external-secret.yaml
  - wordpress-bootstrap-job.yaml
  - db-instance.yaml
transformers:
  - db-instance-namespace-patch.yaml
labels:
  - pairs:
      app.kubernetes.io/instance: staging
    includeSelectors: true
images:
  - name: ghcr.io/sgfdevs/hack4goodsgf.com
    newTag: 1.2.1
patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: hack4goodsgf
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: hack4goodsgf-tls
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: hack4goodsgf
