apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hack4goodsgf-wordpress-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: hack4goodsgf-wordpress-admin
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: WORDPRESS_ADMIN_USER
      remoteRef:
        key: hack4goodsgf/staging/wordpress-admin
        property: username
    - secretKey: WORDPRESS_ADMIN_PASSWORD
      remoteRef:
        key: hack4goodsgf/staging/wordpress-admin
        property: password
    - secretKey: WORDPRESS_ADMIN_EMAIL
      remoteRef:
        key: hack4goodsgf/staging/wordpress-admin
        property: email
