apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: ssh://git@github.com/sgfdevs/infra-k8s-apps.git
    path: src/k8s/platform/argocd/install
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: argocd-secret
      namespace: argocd
      jsonPointers:
        - /data
    - group: external-secrets.io
      kind: ExternalSecret
      name: dex-argocd-client-secret
      namespace: argocd
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.data[].remoteRef.nullBytePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
