apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: ssh://git@github.com/sgfdevs/infra-k8s-apps.git
    targetRevision: main
    path: src/k8s/platform/storage/seaweedfs-db
  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
