injector:
  enabled: false
csi:
  enabled: false
server:
  updateStrategyType: RollingUpdate
  podManagementPolicy: Parallel
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/openbao/data"
          retry_join {
            leader_api_addr = "http://openbao-0.openbao-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://openbao-1.openbao-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://openbao-2.openbao-internal:8200"
          }
        }

        service_registration "kubernetes" {}

        seal "static" {
          current_key_id = "openbao-unseal-v1"
          current_key    = "file:///openbao/seals/current.key"
        }
  dataStorage:
    enabled: true
    size: 10Gi
  extraEnvironmentVars:
    SSL_CERT_DIR: /etc/ssl/certs
    BAO_LOG_FORMAT: json
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
