apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openbao
resources:
  - ../backup-base
  - namespace.yaml
  - backup-serviceaccount.yaml
  - externalsecret-backup-credentials.yaml
  - recovery-configmap.yaml
  - recovery-rbac.yaml
  - middleware-https-redirect.yaml
  - certificate.yaml
  - ingress.yaml
patches:
  - path: backup-patch.yaml
    target:
      group: k8up.io
      version: v1
      kind: PreBackupPod
      name: app-backup
  - path: schedule-patch.yaml
    target:
      group: k8up.io
      version: v1
      kind: Schedule
      name: app-backup
