apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-recovery-state
data: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openbao-recovery
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["openbao-recovery-state"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openbao-recovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openbao-recovery
subjects:
  - kind: ServiceAccount
    name: openbao
    namespace: openbao
