- op: replace
  path: /metadata/name
  value: openbao-backup
- op: replace
  path: /spec/backend/repoPasswordSecretRef/name
  value: openbao-k8up-repo-password
- op: replace
  path: /spec/backend/b2/path
  value: openbao
- op: replace
  path: /spec/backup/schedule
  value: '0 */6 * * *'
- op: replace
  path: /spec/backup/labelSelectors/0/matchLabels/backup.k8up.io~1app
  value: openbao
