apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-helmchartconfig.yaml
  - cloudflared-sgfdevs-token.yaml
  - cloudflared-opensgf-token.yaml
  - lz-headscale-store.yaml
  - traefik-tailnet-auth.yaml
  - traefik-ingress-policy.yaml
  - traefik-dashboard-ingress
