apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-helmchartconfig.yaml
  - middleware-client-headers.yaml
  - middleware-crowdsec.yaml
  - traefik-ingress-policy.yaml
  - traefik-dashboard-ingress
