apiVersion: v1
kind: ServiceAccount
metadata:
  name: sgfdevs-tailnet-secrets
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "-4"
    infra.sgf.dev/aws-role-arn: "arn:aws:iam::${LZ_AWS_ACCOUNT_ID}:role/SGFDevsTailnetParameterReader"
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: lz-headscale
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "-3"
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: sgfdevs-tailnet-secrets
