apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-tailnet-auth
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lz-headscale
    kind: SecretStore
  target:
    name: traefik-tailnet-auth
    creationPolicy: Owner
  data:
    - secretKey: authkey
      remoteRef:
        key: /homelab/headscale/pods/sgfdevs/ingress-gateway-auth-key
