apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: methodconf-tls
spec:
  secretName: methodconf-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - staging.methodconf.com
    - cms-staging.methodconf.com
