apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-s3-tls
  namespace: seaweedfs
spec:
  secretName: seaweedfs-s3-tls
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - uploads.projects.sgf.dev
