apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gooddads-enrollment-bot-application
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: gooddads-enrollment-bot-application
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: gooddads-enrollment-bot/staging/laravel
        property: appKey
    - secretKey: NEON_BASE_URL
      remoteRef:
        key: gooddads-enrollment-bot/staging/neon
        property: neonBaseUrl
    - secretKey: NEON_API_KEY
      remoteRef:
        key: gooddads-enrollment-bot/staging/neon
        property: neonApiKey
    - secretKey: DROPBOX_APP_KEY
      remoteRef:
        key: gooddads-enrollment-bot/staging/dropbox
        property: dropboxAppKey
    - secretKey: DROPBOX_APP_SECRET
      remoteRef:
        key: gooddads-enrollment-bot/staging/dropbox
        property: dropboxAppSecret
    - secretKey: DROPBOX_OAUTH_BASIC_USER
      remoteRef:
        key: gooddads-enrollment-bot/staging/oauth
        property: dropboxOauthBasicUser
    - secretKey: DROPBOX_OAUTH_BASIC_PASSWORD
      remoteRef:
        key: gooddads-enrollment-bot/staging/oauth
        property: dropboxOauthBasicPassword
    - secretKey: SENTRY_LARAVEL_DSN
      remoteRef:
        key: gooddads-enrollment-bot/staging/sentry
        property: sentryDsn
    - secretKey: MAIL_INTAKE_FORM_RECIPIENTS
      remoteRef:
        key: gooddads-enrollment-bot/staging/notifications
        property: mailIntakeFormRecipient
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gooddads-enrollment-bot-ses
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: gooddads-enrollment-bot-ses
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: gooddads-enrollment-bot/staging/ses
        property: username
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: gooddads-enrollment-bot/staging/ses
        property: password
