apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: gooddads-enrollment-bot-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterDef: mysql
  topology: semisync
  terminationPolicy: WipeOut
  componentSpecs:
    - name: mysql
      componentDef: mysql-8.4-1.0.2
      serviceVersion: 8.4.7
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
