- op: replace
  path: /spec/data/0/remoteRef/key
  value: sgf-dev/production/meetup
- op: replace
  path: /spec/data/1/remoteRef/key
  value: sgf-dev/production/sentry
- op: replace
  path: /spec/data/2/remoteRef/key
  value: sgf-dev/production/ses
- op: replace
  path: /spec/data/3/remoteRef/key
  value: sgf-dev/production/ses
