- op: replace
  path: /metadata/name
  value: sgf-dev-backup
- op: replace
  path: /spec/backend/repoPasswordSecretRef/name
  value: sgf-dev-k8up-repo-password
- op: replace
  path: /spec/backend/s3/bucket
  value: sgfdevs-on-prem-k3s-backups/sgf-dev-production
- op: replace
  path: /spec/backup/schedule
  value: "0 8 * * *"
- op: replace
  path: /spec/backup/labelSelectors/0/matchLabels/backup.k8up.io~1app
  value: sgf-dev
