apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kaneo-tls
spec:
  secretName: kaneo-tls
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - projects.sgf.dev
