apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: https://openbao.openbao.svc.cluster.local:8200
      path: applications
      version: v2
      caProvider:
        type: ConfigMap
        name: kube-root-ca.crt
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: kaneo-secrets
          serviceAccountRef:
            name: kaneo-secrets
            audiences:
              - vault
