apiVersion: cache.keiailab.io/v1alpha2
kind: Valkey
metadata:
  name: kaneo-valkey
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  mode: Replication
  replicas: 3
  version:
    image: docker.io/valkey/valkey
    version: 9.0.4
    imagePullPolicy: IfNotPresent
  storage:
    ephemeral: true
  persistence:
    mode: None
  auth:
    enabled: true
  autoFailover: true
  additionalConfig:
    min-replicas-to-write: "1"
    min-replicas-max-lag: "10"
  podDisruptionBudget:
    enabled: true
    minAvailable: 2
  pod:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: valkey
                app.kubernetes.io/instance: kaneo-valkey
            topologyKey: kubernetes.io/hostname
  monitoring:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
