apiVersion: cache.keiailab.io/v1alpha2
kind: Valkey
metadata:
  name: kaneo-valkey
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  mode: Standalone
  version:
    image: docker.io/valkey/valkey
    version: 9.0.4
    imagePullPolicy: IfNotPresent
  storage:
    ephemeral: true
  persistence:
    mode: None
  auth:
    enabled: true
  monitoring:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
