apiVersion: v1
kind: ConfigMap
metadata:
  name: sgf-dev
data:
  SGFDevs__Site__AnalyticsEnabled: "false"
  SGFDevs__Site__SearchIndexingEnabled: "false"
  Umbraco__CMS__Global__Smtp__From: Sgf Devs <website-staging@sgf.dev>
  Umbraco__CMS__WebRouting__UmbracoApplicationUrl: https://staging.sgf.dev
