- op: replace
  path: /spec/data/0/remoteRef/key
  value: sgf-dev/staging/application
- op: replace
  path: /spec/data/1/remoteRef/key
  value: sgf-dev/staging/application
- op: replace
  path: /spec/data/2/remoteRef/key
  value: sgf-dev/staging/application
- op: replace
  path: /spec/data/3/remoteRef/key
  value: sgf-dev/staging/ses
- op: replace
  path: /spec/data/4/remoteRef/key
  value: sgf-dev/staging/ses
