- op: replace
  path: /spec/data/0/remoteRef/key
  value: sgf-dev/staging/meetup
- op: replace
  path: /spec/data/1/remoteRef/key
  value: sgf-dev/staging/sentry
- op: replace
  path: /spec/data/2/remoteRef/key
  value: sgf-dev/staging/ses
- op: replace
  path: /spec/data/3/remoteRef/key
  value: sgf-dev/staging/ses
