- op: replace
  path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
  value: sgf-dev-staging-sgf-dev-https-redirect@kubernetescrd
- op: replace
  path: /spec/tls/0/hosts
  value:
    - staging.sgf.dev
- op: replace
  path: /spec/rules/0/host
  value: staging.sgf.dev
