apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sgf-dev-staging
resources:
- ../base
- namespace.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: staging
images:
- name: ghcr.io/sgfdevs/sgf.dev
  newTag: 1.8.3
patches:
- path: configmap-patch.yaml
- path: deployment-patch.yaml
- path: environment-patch.yaml
  target:
    kind: SecretStore
    name: openbao
- path: external-secret-patch.yaml
  target:
    kind: ExternalSecret
    name: sgf-dev
- path: certificate-patch.yaml
  target:
    kind: Certificate
    name: sgf-dev-tls
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: sgf-dev
