apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sgf-dev-staging
resources:
- ../base
- ../../../platform/services/backup-base
- media-ingress.yaml
- media-path-middleware.yaml
- namespace.yaml
- backup-serviceaccount.yaml
- externalsecret-backup-credentials.yaml
- workflow-rbac.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: staging
images:
- name: ghcr.io/sgfdevs/sgf.dev
  newTag: 1.10.1
patches:
- path: configmap-patch.yaml
- path: backup-patch.yaml
  target:
    group: k8up.io
    kind: PreBackupPod
    name: app-backup
    version: v1
- path: schedule-patch.yaml
  target:
    group: k8up.io
    kind: Schedule
    name: app-backup
    version: v1
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=sgf-dev
    version: v1
- path: environment-patch.yaml
  target:
    kind: SecretStore
    name: openbao
- path: external-secret-patch.yaml
  target:
    kind: ExternalSecret
    name: sgf-dev
- path: certificate-patch.yaml
  target:
    kind: Certificate
    name: sgf-dev-tls
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: sgf-dev
