apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sgf-dev-backup-workflow
rules:
  - apiGroups: ["k8up.io"]
    resources: ["backups"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sgf-dev-backup-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sgf-dev-backup-workflow
subjects:
  - kind: ServiceAccount
    name: sgf-dev-staging-backup
    namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sgf-dev-restore-workflow
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["sgf-dev", "sgf-dev-writer"]
    verbs: ["get"]
  - apiGroups: ["k8up.io"]
    resources: ["backups"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sgf-dev-restore-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sgf-dev-restore-workflow
subjects:
  - kind: ServiceAccount
    name: sgf-dev-staging-restore
    namespace: argo-workflows
