apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: owncloud-backup
spec:
  schedules:
    - "0 3 * * *"
  timezone: America/Chicago
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  workflowSpec:
    workflowTemplateRef:
      name: owncloud-backup
