apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: owncloud-backup
spec:
  schedules:
    - "0 8 * * *"
  timezone: UTC
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  workflowSpec:
    workflowTemplateRef:
      name: owncloud-backup
