directives:
  default-src:
    - "'none'"
  child-src:
    - "'self'"
  connect-src:
    - "'self'"
    - "blob:"
    - "https://id.sgf.dev"
  font-src:
    - "'self'"
    - "data:"
  frame-ancestors:
    - "'self'"
  frame-src:
    - "'self'"
    - "blob:"
    - "https://office.sgf.dev"
    - "https://id.sgf.dev"
  img-src:
    - "'self'"
    - "data:"
    - "blob:"
    - "https://office.sgf.dev"
  manifest-src:
    - "'self'"
  media-src:
    - "'self'"
  object-src:
    - "'self'"
    - "blob:"
  script-src:
    - "'self'"
    - "'unsafe-inline'"
  style-src:
    - "'self'"
    - "'unsafe-inline'"
