apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: owncloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: owncloud
    creationPolicy: Owner
  data:
    - secretKey: IDM_ADMIN_PASSWORD
      remoteRef:
        key: owncloud/app
        property: idmAdminPassword
    - secretKey: WEB_OIDC_CLIENT_ID
      remoteRef:
        key: owncloud/oidc
        property: clientId
    - secretKey: PROXY_OIDC_ACCESS_TOKEN_VERIFY_AUD
      remoteRef:
        key: owncloud/oidc
        property: clientId
    - secretKey: OCIS_OIDC_ISSUER
      remoteRef:
        key: owncloud/oidc
        property: issuer
    - secretKey: NOTIFICATIONS_SMTP_USERNAME
      remoteRef:
        key: owncloud/ses
        property: username
    - secretKey: NOTIFICATIONS_SMTP_PASSWORD
      remoteRef:
        key: owncloud/ses
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: collabora
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: collabora
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: owncloud/app
        property: collaboraAdminPassword
