apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-state
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    # Independent PVC backups are not consistent with the S3 file contents.
    k8up.io/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collabora-proof-key
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    k8up.io/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
