apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - cache-reader.yaml
  - cache-store.yaml
  - ssm-cache.yaml
  - dex-ssm-split.yaml
  - readers.yaml
