apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-discovery-proxy-kubeconfig
  namespace: k8s-oidc
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: local
        cluster:
          server: https://kubernetes.default.svc
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
      - name: oidc-discovery-proxy
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
      - name: oidc-discovery-proxy
        context:
          cluster: local
          user: oidc-discovery-proxy
    current-context: oidc-discovery-proxy
