apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-oidc
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - kubeconfig.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - middleware-strip-authorization.yaml
  - ingressroute.yaml
