apiVersion: v1
kind: Service
metadata:
  name: oidc-discovery-proxy
  namespace: k8s-oidc
spec:
  selector:
    app.kubernetes.io/name: oidc-discovery-proxy
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
