apiVersion: v1
kind: ConfigMap
metadata:
  name: hack4goodsgf
data:
  WORDPRESS_HOME: https://hack4goodsgf.com.invalid
  WORDPRESS_SITEURL: https://hack4goodsgf.com.invalid
  WORDPRESS_TABLE_PREFIX: wp_
  WORDPRESS_SMTP_HOST: email-smtp.us-east-2.amazonaws.com
  WORDPRESS_SMTP_PORT: "587"
  WORDPRESS_SMTP_ENCRYPTION: tls
  WORDPRESS_SMTP_FROM_NAME: Hack4Good SGF
  WORDPRESS_CONFIG_EXTRA: |
    if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
        $_SERVER['HTTPS'] = 'on';
    }
    define('WP_HOME', getenv('WORDPRESS_HOME'));
    define('WP_SITEURL', getenv('WORDPRESS_SITEURL'));
    define('WP_REDIS_HOST', 'hack4goodsgf-valkey');
    define('WP_REDIS_PORT', 6379);
    define('WP_REDIS_PASSWORD', getenv('WORDPRESS_REDIS_PASSWORD'));
    define('WP_CACHE', true);
