apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql-cluster-migration.yaml
  - valkey.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - middleware-https-redirect.yaml
  - certificate.yaml
  - ingress.yaml
