apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: hack4goodsgf
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterDef: redis
  topology: replication
  terminationPolicy: Delete
  componentSpecs:
    - name: redis
      componentDef: redis-8-1.0.2-probe5
      serviceVersion: 8.4.0
      replicas: 2
      systemAccounts:
        - name: default
          passwordConfig:
            length: 32
            numDigits: 8
            numSymbols: 0
            letterCase: MixedCases
      schedulingPolicy:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: hack4goodsgf
                    apps.kubeblocks.io/component-name: redis
                topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      volumes:
        - name: data
          emptyDir: {}
    - name: redis-sentinel
      componentDef: redis-sentinel-8-1.0.2
      serviceVersion: 8.4.0
      replicas: 3
      systemAccounts:
        - name: default
          passwordConfig:
            length: 32
            numDigits: 8
            numSymbols: 0
            letterCase: MixedCases
      schedulingPolicy:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: hack4goodsgf
                    apps.kubeblocks.io/component-name: redis-sentinel
                topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
