apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: methodconf-backup-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: k8up-b2-credentials
    creationPolicy: Owner
  data:
    - secretKey: account-id
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/backups/b2-account-id
    - secretKey: account-key
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/backups/b2-account-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: methodconf-k8up-repo-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: methodconf-k8up-repo-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: methodconf/production/backup
        property: resticPassword
