- op: replace
  path: /metadata/name
  value: plausible-backup
- op: replace
  path: /metadata/labels/backup.k8up.io~1app
  value: plausible
- op: replace
  path: /spec/fileExtension
  value: .dump
- op: replace
  path: /spec/backupCommand
  value: >-
    sh -ec 'pg_dump
    --host=plausible-db-rw
    --username=plausible
    --dbname=plausible
    --format=custom
    --no-owner
    --no-privileges'
- op: replace
  path: /spec/pod/spec/serviceAccountName
  value: plausible-backup
- op: add
  path: /spec/pod/spec/automountServiceAccountToken
  value: false
- op: replace
  path: /spec/pod/spec/containers/0/image
  value: ghcr.io/cloudnative-pg/postgresql:18.6-system-trixie
- op: replace
  path: /spec/pod/spec/containers/0/resources/requests/memory
  value: 64Mi
- op: add
  path: /spec/pod/spec/containers/0/env
  value:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: plausible-db-app
          key: password
    - name: PGSSLMODE
      value: require
