apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  BASE_URL: https://plausible.sgf.dev
  HTTP_PORT: "8000"
  LISTEN_IP: "0.0.0.0"
  DISABLE_REGISTRATION: invite_only
  ENABLE_EMAIL_VERIFICATION: "true"
  DATA_DIR: /var/lib/plausible
  TMPDIR: /var/lib/plausible/tmp
  MAILER_ADAPTER: Bamboo.Mua
  SMTP_HOST_SSL_ENABLED: "false"
