apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plausible
resources:
  - ../../platform/services/backup-base
  - namespace.yaml
  - identity.yaml
  - secrets.yaml
  - configmap.yaml
  - database.yaml
  - clickhouse.yaml
  - pvc.yaml
  - install-job.yaml
  - deployment.yaml
  - service.yaml
  - backup-keys.yaml
  - backup-workflowtemplate.yaml
  - restore-workflowtemplate.yaml
  - restore-resume-workflowtemplate.yaml
  - workflow-scripts.yaml
  - workflow-rbac.yaml
  - monitoring.yaml
patches:
  - path: backup-patch.yaml
    target:
      group: k8up.io
      version: v1
      kind: PreBackupPod
      name: app-backup
  - path: schedule-patch.yaml
    target:
      group: k8up.io
      version: v1
      kind: Schedule
      name: app-backup
configMapGenerator:
  - name: plausible-clickhouse-config
    files:
      - server.xml=clickhouse/server.xml
  - name: plausible-clickhouse-scripts
    files:
      - backup.sh=clickhouse/backup.sh
      - restore.sh=clickhouse/restore.sh
