apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-data
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    k8up.io/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
