apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: outline-sgfdevs
resources:
  - ../base
  - namespace.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: outline
      data:
        URL: https://docs.sgf.dev
        AWS_S3_UPLOAD_BUCKET_NAME: sgfdevs-outline-assets
        SMTP_FROM_EMAIL: SGF Devs Docs <outline@sgf.dev>
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: outline-secrets
        annotations:
          infra.sgf.dev/aws-role-arn: "arn:aws:iam::${SGFDEVS_AWS_ACCOUNT_ID}:role/sgfdevs-k3s/sgfdevs-k3s-outline-sgfdevs"
  - patch: |-
      apiVersion: external-secrets.io/v1
      kind: SecretStore
      metadata:
        name: openbao
      spec:
        provider:
          vault:
            auth:
              kubernetes:
                role: outline-sgfdevs-secrets
  - target:
      kind: ExternalSecret
      name: outline
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: outline/sgfdevs/secret-key
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: outline/sgfdevs/utils-secret
      - op: replace
        path: /spec/data/2/remoteRef/key
        value: outline/sgfdevs/ses
      - op: replace
        path: /spec/data/3/remoteRef/key
        value: outline/sgfdevs/ses
  - target:
      kind: Ingress
      name: outline
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: docs.sgf.dev
      - op: replace
        path: /spec/rules/1/host
        value: outline.sgf.dev
