apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-argocd-reader
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-argocd-reader
  namespace: external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["argocd-secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectrulesreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-argocd-reader
  namespace: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-argocd-reader
subjects:
  - kind: ServiceAccount
    name: eso-argocd-reader
    namespace: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-grafana-reader
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-grafana-reader
  namespace: external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["grafana-secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectrulesreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-grafana-reader
  namespace: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-grafana-reader
subjects:
  - kind: ServiceAccount
    name: eso-grafana-reader
    namespace: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-oauth2-proxy-reader
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-oauth2-proxy-reader
  namespace: external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["oauth2-proxy-secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectrulesreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-oauth2-proxy-reader
  namespace: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-oauth2-proxy-reader
subjects:
  - kind: ServiceAccount
    name: eso-oauth2-proxy-reader
    namespace: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-dex-reader
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-dex-reader
  namespace: external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["dex-secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectrulesreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-dex-reader
  namespace: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-dex-reader
subjects:
  - kind: ServiceAccount
    name: eso-dex-reader
    namespace: external-secrets
