apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ssm-cache
  namespace: external-secrets
  annotations:
    external-secrets.io/force-sync: "1"
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: ssm-cache
  data:
    - secretKey: githubClientSecret
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/dex-github-oauth-client-secret
    - secretKey: cookieSecret
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/oauth2-proxy-cookie-secret
    - secretKey: argoWorkflowsClientSecret
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/dex-argo-workflows-client-secret
    - secretKey: argocdClientSecret
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/dex-argocd-client-secret
    - secretKey: grafanaClientSecret
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/dex-grafana-client-secret
    - secretKey: oauth2ProxyClientSecret
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/dex-oauth2-proxy-client-secret
    - secretKey: openbaoClientSecret
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/dex-openbao-client-secret
