apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wekan-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: wekan-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: OAUTH2_CLIENT_ID
      remoteRef:
        key: wekan/oidc
        property: clientId
    - secretKey: OAUTH2_SECRET
      remoteRef:
        key: wekan/oidc
        property: clientSecret
