apiVersion: v1
kind: Service
metadata:
  name: wekan
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: wekan-affinity
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: lax
  labels:
    app.kubernetes.io/name: wekan
spec:
  selector:
    app.kubernetes.io/name: wekan
  ports:
    - name: http
      port: 80
      targetPort: http
