apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflows
resources:
  - workflow-rbac.yaml
  - workflow-scripts.yaml
  - staging-backup-workflowtemplate.yaml
  - staging-restore-workflowtemplate.yaml
  - production-backup-workflowtemplate.yaml
  - production-restore-workflowtemplate.yaml
