apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-objstore-config
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: observability-k8s
  target:
    name: thanos-objstore-config
    template:
      engineVersion: v2
      data:
        objstore.yml: |
          type: S3
          config:
            bucket: thanos-metrics
            endpoint: seaweedfs-s3.seaweedfs.svc.cluster.local:8333
            region: us-east-1
            insecure: true
            access_key: {{ .accessKeyId }}
            secret_key: {{ .secretAccessKey }}
  data:
    - secretKey: accessKeyId
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: seaweedfs-s3-observability
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: AWS_ACCESS_KEY_ID
    - secretKey: secretAccessKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: seaweedfs-s3-observability
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: AWS_SECRET_ACCESS_KEY
