apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: outline
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: outline/instance/secret-key
        property: secretKey
    - secretKey: UTILS_SECRET
      remoteRef:
        key: outline/instance/utils-secret
        property: utilsSecret
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: outline/instance/ses
        property: username
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: outline/instance/ses
        property: password
