apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: alloy-config
    namespace: observability
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
      annotations:
        argocd.argoproj.io/sync-wave: "0"
