apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
        configmap.reloader.stakater.com/reload: "argocd-cm,argocd-cmd-params-cm"
    spec:
      containers:
        - name: argocd-server
          resources:
            requests:
              cpu: 10m
              memory: 96Mi
            limits:
              memory: 256Mi
