apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, sgfdevs:infra-platform-admins, role:admin
    g, sgfdevs:infra-maintainers, role:admin
  scopes: "[groups]"
