apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-redis-ha-server
spec:
  template:
    spec:
      initContainers:
        - name: config-init
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 128Mi
      containers:
        - name: redis
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              memory: 128Mi
        - name: sentinel
          resources:
            requests:
              cpu: 25m
              memory: 16Mi
            limits:
              memory: 64Mi
        - name: split-brain-fix
          resources:
            requests:
              cpu: 10m
              memory: 8Mi
            limits:
              memory: 32Mi
