apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
        configmap.reloader.stakater.com/reload: "argocd-cm,argocd-cmd-params-cm"
