apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-grafana-client-secret
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: grafana-k8s
  target:
    name: dex-grafana-client-secret
  data:
    - secretKey: GF_OAUTH_CLIENT_SECRET
      remoteRef:
        key: grafana-secrets
        property: grafanaClientSecret
