apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: healthiermo
resources:
  - namespace.yaml
  - mysql-cluster.yaml
  - database.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
transformers:
  - db-instance-namespace-patch.yaml
configMapGenerator:
  - name: healthiermo-schema
    files:
      - schema.sql
