- op: replace
  path: /metadata/name
  value: healthiermo-backup
- op: add
  path: /metadata/annotations
  value:
    argocd.argoproj.io/sync-wave: "4"
- op: replace
  path: /spec/backend/repoPasswordSecretRef/name
  value: healthiermo-k8up-repo-password
- op: replace
  path: /spec/backend/s3/bucket
  value: sgfdevs-on-prem-k3s-backups/healthiermo
- op: replace
  path: /spec/backup/labelSelectors/0/matchLabels/backup.k8up.io~1app
  value: healthiermo
