apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dex-k8s
  target:
    name: dex-secrets
  dataFrom:
    - extract:
        key: dex-secrets
