apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valkey-sentinel
resources:
  - namespace.yaml
  - auth.yaml
  - service.yaml
  - statefulset.yaml
  - pdb.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: valkey-sentinel-config
    files:
      - sentinel.conf
      - start.sh
      - probe.sh
