apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: app-backup
spec:
  backend:
    repoPasswordSecretRef:
      name: app-k8up-repo-password
      key: password
    s3:
      endpoint: https://s3.us-east-005.backblazeb2.com
      bucket: sgfdevs-on-prem-k3s-backups/app
      accessKeyIDSecretRef:
        name: k8up-b2-credentials
        key: account-id
      secretAccessKeySecretRef:
        name: k8up-b2-credentials
        key: account-key
  backup:
    schedule: '0 8 * * *'
    activeDeadlineSeconds: 1800
    clusterName: sgfdevs
    promURL: http://prometheus-pushgateway.observability.svc.cluster.local:9091
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    labelSelectors:
      - matchLabels:
          backup.k8up.io/app: app
  check:
    schedule: '0 9 * * 1'
    activeDeadlineSeconds: 1800
  prune:
    schedule: '0 10 * * 0'
    activeDeadlineSeconds: 1800
    retention:
      keepLast: 5
      keepDaily: 14
      keepWeekly: 4
