apiVersion: v1
kind: ConfigMap
metadata:
  name: listmonk
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  LISTMONK_app__address: 0.0.0.0:9000
  LISTMONK_db__host: listmonk-db-rw
  LISTMONK_db__port: "5432"
  LISTMONK_db__user: listmonk
  LISTMONK_db__database: listmonk
  LISTMONK_db__ssl_mode: require
  LISTMONK_db__max_open: "20"
  LISTMONK_db__max_idle: "5"
  LISTMONK_db__max_lifetime: 300s
  TZ: Etc/UTC
