apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: listmonk
resources:
  - ../../platform/services/backup-base
  - namespace.yaml
  - identity.yaml
  - secrets.yaml
  - configmap.yaml
  - database.yaml
  - install-job.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml
  - middleware-https-redirect.yaml
  - backup-workflowtemplate.yaml
  - restore-workflowtemplate.yaml
  - restore-resume-workflowtemplate.yaml
  - workflow-scripts.yaml
  - workflow-rbac.yaml
patches:
  - path: backup-patch.yaml
    target:
      group: k8up.io
      version: v1
      kind: PreBackupPod
      name: app-backup
  - path: schedule-patch.yaml
    target:
      group: k8up.io
      version: v1
      kind: Schedule
      name: app-backup
configMapGenerator:
  - name: listmonk-settings
    files:
      - settings.sql
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
