apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: listmonk
resources:
  - namespace.yaml
  - identity.yaml
  - secrets.yaml
  - configmap.yaml
  - database.yaml
  - install-job.yaml
  - deployment.yaml
  - service.yaml
  - backup.yaml
configMapGenerator:
  - name: listmonk-settings
    files:
      - settings.json
      - settings.sql
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
