apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: listmonk-smtp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: listmonk-smtp
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        settings.json: |
          {
            "app.root_url": "https://newsletter.sgf.dev",
            "app.from_email": {{ .fromAddress | toJson }},
            "smtp": [
              {
                "name": "email-ses",
                "uuid": "ec1584be-265a-4fb3-aaf6-4821d3439d08",
                "enabled": true,
                "host": {{ .host | toJson }},
                "port": {{ .port | atoi }},
                "username": {{ .username | toJson }},
                "password": {{ .password | toJson }},
                "hello_hostname": "",
                "auth_protocol": "login",
                "max_conns": 2,
                "idle_timeout": "15s",
                "wait_timeout": "5s",
                "max_msg_retries": 2,
                "tls_type": "STARTTLS",
                "tls_skip_verify": false,
                "email_headers": [
                  {"X-SES-CONFIGURATION-SET": {{ .configurationSet | toJson }}}
                ]
              }
            ],
            "upload.provider": "s3",
            "upload.s3.url": "https://s3.us-east-2.amazonaws.com",
            "upload.s3.public_url": "/uploads",
            "upload.s3.aws_access_key_id": "",
            "upload.s3.aws_secret_access_key": "",
            "upload.s3.aws_default_region": "us-east-2",
            "upload.s3.bucket": "sgfdevs-listmonk-uploads",
            "upload.s3.bucket_domain": "",
            "upload.s3.bucket_path": "",
            "upload.s3.bucket_type": "private",
            "upload.s3.expiry": "1h"
          }
  dataFrom:
    - extract:
        key: listmonk/ses
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: listmonk-k8up-repo-password
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: listmonk-k8up-repo-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: listmonk/backup
        property: resticPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: listmonk-backup-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: k8up-b2-credentials
    creationPolicy: Owner
  data:
    - secretKey: account-id
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/backups/b2-account-id
    - secretKey: account-key
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/backups/b2-account-key
