nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - kind: PreBackupPod
        path: spec/pod/spec/containers/envFrom/configMapRef/name
      - kind: WorkflowTemplate
        path: spec/templates/container/envFrom/configMapRef/name
      - kind: WorkflowTemplate
        path: spec/templates/volumes/configMap/name
