apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glitchtip-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: glitchtip-app
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: glitchtip/app
        property: secretKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glitchtip-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: glitchtip-oidc
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: glitchtip/oidc
        property: clientId
    - secretKey: OIDC_DISCOVERY_URL
      remoteRef:
        key: glitchtip/oidc
        property: discoveryUrl
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glitchtip-smtp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: glitchtip-smtp
    creationPolicy: Owner
  data:
    - secretKey: EMAIL_HOST
      remoteRef:
        key: glitchtip/ses
        property: host
    - secretKey: EMAIL_PORT
      remoteRef:
        key: glitchtip/ses
        property: port
    - secretKey: EMAIL_HOST_USER
      remoteRef:
        key: glitchtip/ses
        property: username
    - secretKey: EMAIL_HOST_PASSWORD
      remoteRef:
        key: glitchtip/ses
        property: password
    - secretKey: DEFAULT_FROM_EMAIL
      remoteRef:
        key: glitchtip/ses
        property: fromAddress
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glitchtip-k8up-repo-password
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: glitchtip-k8up-repo-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: glitchtip/backup
        property: resticPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glitchtip-backup-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: k8up-b2-credentials
    creationPolicy: Owner
  data:
    - secretKey: account-id
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/backups/b2-account-id
    - secretKey: account-key
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/backups/b2-account-key
