apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-sgfdevs-token
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: cloudflared-sgfdevs-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /vm-workloads/sgfdevs/infra-vm-workloads/cloudflare-sgfdevs-tunnel-token
