apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
resources:
  - namespace.yaml
  - externalsecret-sgfdevs.yaml
  - externalsecret-opensgf.yaml
  - deployment-sgfdevs.yaml
  - deployment-opensgf.yaml
  - pdb-sgfdevs.yaml
  - pdb-opensgf.yaml
  - networkpolicy.yaml
