apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared-opensgf
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/instance: opensgf
