apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-k8s-apps-bootstrap-controllers
  namespace: flux-system
spec:
  interval: 5m
  path: ./src/k8s/bootstrap/controllers
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: infra-k8s-apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-k8s-apps-bootstrap-config
  namespace: flux-system
spec:
  interval: 5m
  path: ./src/k8s/bootstrap/config
  prune: true
  wait: true
  dependsOn:
    - name: infra-k8s-apps-bootstrap-controllers
  sourceRef:
    kind: GitRepository
    name: infra-k8s-apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-k8s-apps-apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./src/k8s/apps
  prune: true
  wait: true
  dependsOn:
    - name: infra-k8s-apps-bootstrap-config
  sourceRef:
    kind: GitRepository
    name: infra-k8s-apps
