apiVersion: v1
kind: ConfigMap
metadata:
  name: methodconf-cms
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  ConnectionStrings__umbracoDbDSN: Data Source=/var/lib/methodconf/Umbraco.sqlite.db;Cache=Shared;Foreign Keys=True;Pooling=True;Default Timeout=60
  Umbraco__CMS__Global__DisableElectionForSingleServer: "true"
  Umbraco__CMS__Global__DistributedLockingMechanism: SqliteDistributedLockingMechanism
  Umbraco__CMS__Global__Smtp__Host: email-smtp.us-east-2.amazonaws.com
  Umbraco__CMS__Global__Smtp__Port: "587"
  Umbraco__CMS__Global__Smtp__SecureSocketOptions: StartTls
  uSync__Settings__ExportAtStartup: None
  uSync__Settings__ExportOnSave: None
  uSync__Settings__ImportAtStartup: None
  uSync__Settings__ImportOnFirstBoot: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: methodconf-frontend
data:
  NEWSLETTER_ENDPOINT: https://newsletter.sgf.dev/api/public/subscription
  UMBRACO_BASE_URL: http://methodconf-cms
