apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: methodconf-cms
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: methodconf-cms
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: Umbraco__CMS__Global__Smtp__Username
      remoteRef:
        key: methodconf/ses
        property: username
    - secretKey: Umbraco__CMS__Global__Smtp__Password
      remoteRef:
        key: methodconf/ses
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: methodconf-frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: methodconf-frontend
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: NEWSLETTER_LIST_ID
      remoteRef:
        key: methodconf/application
        property: newsletterListId
