apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: outline-opensgf
resources:
  - ../base
  - namespace.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: outline
      data:
        URL: https://docs.opensgf.org
        AWS_S3_UPLOAD_BUCKET_NAME: opensgf-outline-assets
        SMTP_FROM_EMAIL: Open SGF Docs <opensgf-outline@sgf.dev>
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: outline-secrets
        annotations:
          infra.sgf.dev/aws-role-arn: "arn:aws:iam::${SGFDEVS_AWS_ACCOUNT_ID}:role/sgfdevs-k3s/sgfdevs-k3s-outline-opensgf"
  - patch: |-
      apiVersion: external-secrets.io/v1
      kind: SecretStore
      metadata:
        name: openbao
      spec:
        provider:
          vault:
            auth:
              kubernetes:
                role: outline-opensgf-secrets
  - target:
      kind: ExternalSecret
      name: outline
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: outline/opensgf/app
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: outline/opensgf/app
      - op: replace
        path: /spec/data/2/remoteRef/key
        value: outline/opensgf/ses
      - op: replace
        path: /spec/data/3/remoteRef/key
        value: outline/opensgf/ses
  - patch: |-
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: outline-tls
      spec:
        dnsNames:
          - docs.opensgf.org
          - outline.opensgf.org
  - target:
      kind: Ingress
      name: outline
    patch: |-
      - op: add
        path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
        value: outline-opensgf-outline-https-redirect@kubernetescrd,outline-opensgf-outline-canonical@kubernetescrd
      - op: replace
        path: /spec/tls/0/hosts
        value: [docs.opensgf.org, outline.opensgf.org]
      - op: replace
        path: /spec/rules/0/host
        value: docs.opensgf.org
      - op: replace
        path: /spec/rules/1/host
        value: outline.opensgf.org
  - patch: |-
      apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: outline-canonical
      spec:
        redirectRegex:
          regex: '^https?://outline[.]opensgf[.]org/(.*)'
          replacement: 'https://docs.opensgf.org/${1}'
