apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: zitadel-selfsigned
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zitadel-login-service-key
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretName: zitadel-login-service-key
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: zitadel-selfsigned
    kind: Issuer
    group: cert-manager.io
  usages:
    - digital signature
  dnsNames:
    - zitadel-login.zitadel.svc.cluster.local
