apiVersion: v1
kind: ServiceAccount
metadata:
  name: zitadel-backup-workflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zitadel-restore-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zitadel-backup-workflow
rules:
  - apiGroups: ["k8up.io"]
    resources: ["backups"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zitadel-backup-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zitadel-backup-workflow
subjects:
  - kind: ServiceAccount
    name: zitadel-backup-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zitadel-restore-workflow
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["zitadel", "zitadel-login"]
    verbs: ["get", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    resourceNames: ["zitadel", "zitadel-login"]
    verbs: ["get", "patch"]
  - apiGroups: ["k8up.io"]
    resources: ["backups"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zitadel-restore-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zitadel-restore-workflow
subjects:
  - kind: ServiceAccount
    name: zitadel-restore-workflow
