apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  preservedFields:
    annotations:
      - argocd.argoproj.io/skip-reconcile
      - restore.sgf.dev/managed
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy/automated/selfHeal
  generators:
    - git:
        repoURL: ssh://git@github.com/sgfdevs/infra-k8s-apps.git
        revision: main
        files:
          - path: src/k8s/apps/*/kustomization.yaml
          - path: src/k8s/apps/*/*/kustomization.yaml
          - path: src/k8s/apps/*/base/kustomization.yaml
            exclude: true
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{ trimPrefix "src/k8s/apps/" .path.path | replace "/" "-" | replace "." "-" | normalize }}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: apps
      source:
        repoURL: ssh://git@github.com/sgfdevs/infra-k8s-apps.git
        path: '{{.path.path}}'
        targetRevision: main
      destination:
        namespace: '{{ trimPrefix "src/k8s/apps/" .path.path | replace "/" "-" | replace "." "-" | normalize }}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - FailOnSharedResource=true
          - PruneLast=true
