name: Kubernetes PR Checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    uses: glitchedmob/infra-gha/.github/workflows/k8s-pr-checks.yml@v0.11.0
    with:
      kubernetes-version: 1.36.2
      kustomization-roots: |
        src/k8s/bootstrap/operators/base
        src/k8s/bootstrap/operators/dependent
        src/k8s/bootstrap/projects
        src/k8s/apps
        src/k8s/platform
