apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-sso
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: argo-workflows-k8s
  target:
    name: argo-workflows-sso
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        client-id: argo-workflows
        client-secret: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: argo-workflows-secrets
        property: argoWorkflowsClientSecret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
